spring:
  config:
    import: classpath:workflow-config.yml

# 日志配置：输出到文件
logging:
  file:
    name: logs/cf-cb.log
  level:
    root: INFO
    org.example: INFO

mybatis:
  type-handlers-package: org.example.db.config
  configuration:
    map-underscore-to-camel-case: true

codebeamer:
#  base-url-prefix: https://cb-trial.hirain.com
#  username: yangyang.zhang
#  username: 271824611524632704
#  password: yangyang.zhang
  base-url-prefix: https://cb-pmt.hirain.com:8443
  username: zhangjiamin.zhong
  password: zhangjiamin.zhong

  #  春风测试环境
#  base-url-prefix: http://192.168.101.174:8080
#  username: 271824611524632704
#  password: cbroot


dingtalk:
  # 钉钉接口
  base-url-prefix: https://api.dingtalk.com
  message-base-url-prefix: https://oapi.dingtalk.com
  app-key: dingen7uf61izibidx34
  app-secret: oRrTEcxXX-BmtTouwsDBH_6lR4mIe5hHQ9QtTDG2cvD0uJlARHzIk_RuujvlIzmD
  agent-id: 4182157252
  # 春风
  client-base-url-prefix: http://10.32.4.50:10600/papi/openapi
  corp-id: 9420b0c0840fc1e421c4d045d50c3dc

  # 临期*天提醒默认值
  near-expired-default: 5
  # 超期*天提醒部长
  overdue-minister-default: 3
  # 超期*天提醒总监
  overdue-director-default: 5
  # 超期*天后每周一提醒
  overdue-weekly: 8
  # 每天定时任务提醒，默认8点
  notify-cron: "0 53 13 * * ?"
  # 轮询任务，默认30分钟
  fixed-delay: 1800000

server:
  port: 8081

sqlite:
  database-path: data/notification.db
  review-database-path: data/review-notify.db
